FROM python:3.10

WORKDIR /api

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1
ENV ENVIRONMENT local
ENV GUNICORN_CMD_ARGS="--reload"

COPY ./api/requirements.txt .
#COPY requirements-test.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt
#RUN pip install --no-cache-dir --upgrade -r requirements-test.txt

COPY ./api .

CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=8000", "--reload"]