services:
  app:
    image: app_kanban
    container_name: app_kanban
    env_file:
      - ../app/.env
    build:
      context: ../
      dockerfile: ./infrastructure/Dockerfile.app
    volumes:
      - ../app/:/app
    ports:
      - "3000:3000"
    environment:
      - ENV=local
    
  fastapi:
    image: api_kanban
    container_name: api_graphql
    env_file:
      - ../api/.env
    build:
      context: ../
      dockerfile: ./infrastructure/Dockerfile.backend
    volumes:
      - ../api/:/api
    ports:
      - "8000:8000"
    environment:
      - ENV=local
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    ports:
      - 4000:8000
    volumes:
      - ./shared/dynamo:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

